### ISSUE TITLE
Context-menu not working

### ISSUE THREAD

**Issue by FelixRewer** [cryptic-game/frontend#1]
## Description

The context menu isn't work.

## Reproduce

1. Right click on desktop
2. The context menu should show, but it doesn't

## Expected behavior

A grey box should show up. It contains a list of options.

## System

- OS: MacOS
- Browser: Chrome
- Node Version: 10.6.0
- NPM Version: 6.4.1

**Comment by FelixRewer** [comment]
Fixed.

The sytle-binding missed the transforming pipes.

**Comment by Tristan-H11** [comment]
Outdated.
