### ISSUE TITLE
Base Components without Styling

### ISSUE THREAD

**Issue by MarcelCoding** [cryptic-game/frontend#125]
## Description
Add Base Components without Styling.

## Problem
No consistent design.

## Important
Do not merge for now, so that no new interaction elements can be created later.

**Comment by MarcelCoding** [comment]
Do not merge for now, so that no new interaction elements can be created later.

**Comment by DevMimas** [comment]
Dachte das kommt in die v0.3?

**Comment by Tristan-H11** [comment]
Closed in favor of #260
