### ISSUE TITLE
Desktop - add Pre-Alpha 1.0

### ISSUE THREAD

**Issue by DevMimas** [cryptic-game/frontend#13]
Auf dem Desktop oben links in der Ecke "Pre-Alpha 1.0" schreiben, relativ groß und gut sichtbar. Dabei bisschen Abstand zum oberen Rand und zur Seite lassen.

**Comment by FelixRewer** [comment]
Ich bin dumm.

**Comment by Chaozz66** [comment]
habs ins background img eingefügt !

**Comment by FelixRewer** [comment]
Das sollte automatisiert eingeführt werden.

**Comment by MaxiHuHe04** [comment]
eebf8d84
