### ISSUE TITLE
Miner text field for uuid cannot be overwritten

### ISSUE THREAD

**Issue by DevMimas** [cryptic-game/frontend#137]
## Description

Ein Bug ist im Miner-Textfeld aufgetreten.

## Reproduce
1. neues wallet erstellen
2. wallet-uuid mit dem miner verknüpfen
3. wallet löschen
4. neues wallet erstellen
**5. BUG: Wallet-UUID wird im Miner-Textfeld nicht enfernt, wenn wallet gelöscht wird
6. BUG: Wallet-UUID lässt sich im Miner nicht änderen/überschreiben**

## Screenshots (if appropriate)
Video: https://drive.google.com/drive/folders/10bIb_IwB0KcL8SWbuZM0lI_B3aoTXZoU?usp=sharing

## System

We need the following information:
- OS: Windwos 10
- Browser: Firefox 74.0
- Node and NPM version, i don´t now

If you have any questions please cantact me @DevMimas

**Comment by JannikEmmerich** [comment]
Fixed in #139
