### ISSUE TITLE
Add hardware features for hardwareshop

### ISSUE THREAD

**Issue by DevMimas** [cryptic-game/frontend#140]
## Description

In the shop, the hardware features of each hardware must be added - see drawing.
**Technical specifications** for:

- Mainboards
- Processors
- Cooler
- RAM
- Graphic cards
- Disks
- Power Packs
- Cases

If you have any questions please contact to me @DevMimas 

Hier die Reihenfolge wie die Hardwaredaten ausgegeben werden. Alle Daten kommen aus [cryptic device / vars.py](https://github.com/cryptic-game/cryptic-device/blob/experimental/app/vars.py)

## CPU
CPU – CoreOne A100 / Fall 1

**Processor - properties**
`Frequency min.: 500 MHz`
`Frequency max.: 500 MHz`
`Socket: XT2019`
`Number cores: 1`
`Max. temperature: 72°C`
`Power usage: 220 W`
**Processor - specific power:**
`Turbospeed: not available`
`Overclock: not available`
**Processor - graphics:**
`Integrated graphics: not integrated`

CPU – DualCore M101 / Fall 2

**Processor - properties**
`Frequency min.: 800 MHz`
`Frequency max.: 800 MHz`
`Socket: XT2020`
`Number cores: 2`
`Max. temperature: 72°C`
`Power usage: 250 W`
**Processor - specific power:**
`Turbospeed: not available`
`Overclock: not available`
**Processor - graphics:**
`Integrated graphics: HD Graphic 100`
`Memory: 512 MB`
`Frequency: 522 MHz`

## Cooler

**Cooler - properties**
`Cooler speed: 1`
`Socket: XT2019`
`Power usage: 10 W`

## RAM

**RAM - properties**
`RAM size: 128 MB`
`Type: DDR 1`
`Frequency: 422 MHz`
`Power usage: 5 W`

## Graphic cards

**Graphic cards - properties**
`RAM size: 128 MB`
`Type: GDDR 1`
`Frequency: 422 MHz`
`Interface: AGP 1`
`Power usage: 80 W`

## Disk

**Disk - properties**
`Typ: HDD`
`Capacity: 2 GB` --> (Achtung! Muss umgerechnet werden!)
`Interface: IDE 1`
`Writing speed: 8 MB/s`
`Reading speed: 16 MB/s`
`Power usage: 15 W`

## Powerpack

**Powerpack - properties**
`Total power: 500 W`

## Case

**Case - properties**
`Name: Mini-ITX`
`Size: small`

## Problem

Without these features, it is impossible to know the characteristics of the hardware such as CPU frequency, RAM size, compatibility, etc.

## Design
![Hardwareshop_Technische Daten](https://user-images.githubusercontent.com/44207756/78043592-d62e1900-7373-11ea-8120-4bef53e7d3b6.png)

**Comment by JongamerProgramming** [comment]
I would take the issue.

**Comment by SophieErdbeer** [comment]
Hey, I would like to try it :)
