### ISSUE TITLE
Infinite names are accepted by the frontend

### ISSUE THREAD

**Issue by ClientCrash** [cryptic-game/frontend#146]
## Description

The frontend accepts infinite names (length).
This causes a crash of the frontend and many requests could probably also influence the performance of the backend.
## Reproduce
Put a very long String into the name field on sign-up

## Expected behavior

The frontend only accepts names up to 256 characters.

## System

- OS: Windows
- Browser: Chrome

**Comment by JannikEmmerich** [comment]
@MaxiHuHe04 See https://github.com/cryptic-game/java-backend-dev/pull/45
Now we have to add an error message in the frontend.
