### ISSUE TITLE
Texteditor-App

### ISSUE THREAD

**Issue by DevMimas** [cryptic-game/frontend#154]
## Description
A text window that displays the contents of text files. For the first one, the text is displayed read-only.

## Problem
Text files selected in the file manager should be able to be opened. 
You need an additional tool.

## Additional context
**Textfile**
If you double click on a text file in the file manager #57, the text is opened and displayed in a separate window. If you open another text file, it will also be displayed in a separate window.

Window can minimize and close

## Icons from design repo
[Textfile icon](https://github.com/cryptic-game/graphics/tree/master/icons/textdocument)

## Concept
![grafik](https://user-images.githubusercontent.com/44207756/81505959-65bfd380-92f3-11ea-9fe9-9c5b8db599e5.png)

If you have any questions please contact me @DevMimas

**Comment by SophieErdbeer** [comment]
Ich würde das Ticket gern immernoch bearbeiten ;P
