### ISSUE TITLE
Desktop Background after change not saved.

### ISSUE THREAD

**Issue by David-Spudic** [cryptic-game/frontend#155]
**Description**

Since Pre-Alpha 2.0 the function to change the background image was added. This now has a bug.

**Problem**

The problem with the background image is that it is not saved.

a solution would be to implement the background in the variable where the icons are saved after they are moved.

**Comment by JannikEmmerich** [comment]
There is a setting for changing the background image that works well. But what exactly do you mean by "function to change the background color"?

**Comment by David-Spudic** [comment]
> 
> 
> There is a setting for changing the background image that works well. But what exactly do you mean by "function to change the background color"?

Sorry for the confusion, meant the wallpaper (updated the description)

**Comment by JannikEmmerich** [comment]
Can you please tell me the steps for reproducing your issue, because I can't reproduce it, everything works fine for me.

**Comment by David-Spudic** [comment]
Sure!

1. Login to your Computer
2. Nex double Klick on "Settings"
3. Change the Backgroundimage to "White"
4. Klick on the Button "Save" to save the settings
5. Logout from your Computer
6. On the nex Login the Computers Desktop Wallpapers switching back to the default black Wallpaper

**Comment by JannikEmmerich** [comment]
Now I have it. That's because the local storage is cleared when you log out. The frontend should use the settings endpoint of the backend for individual settings.
