### ISSUE TITLE
You can create a folder/file named ".." and cannot interact, even delete it

### ISSUE THREAD

**Issue by cephox** [cryptic-game/frontend#157]
If you create a file called "..", you cannot delete it, read it, rename it, move it, etc.
If you create a folder called "..",  you cannot use it, enter it, delete it, read it, rename it, move it, etc.

**Reproduce**

1. Create a file/folder named ".."
2. Observe it

**Logs**
![grafik](https://user-images.githubusercontent.com/40516991/81797626-54eba980-950f-11ea-9c46-68c06c355060.png)

**System**
Windows 10, Web browser

**Comment by MaxiHuHe04** [comment]
The check for these special file names (also `.`) will just be implemented in the cryptic-device microservice, so we won't have to change anything in the frontend: https://github.com/cryptic-game/cryptic-device/issues/88
