### ISSUE TITLE
Add a switch function from desktop to the control center

### ISSUE THREAD

**Issue by DevMimas** [cryptic-game/frontend#164]
## Description
A switch button that switches from the desktop to the control center.
It can be placed in the **start menu** or in the **upper left corner** of the desktop.

## Problem
You need a way to get back to the control center directly from your desktop.

If you have any questions please contact @DevMimas

**Comment by MaxiHuHe04** [comment]
(At least temporarily) Implemented in https://github.com/cryptic-game/frontend/commit/b1b4c13bddc7c7903bc0a3c5afa1a51a581dda6e
