### ISSUE TITLE
Miner Überweisung Resettet Wallet App Screen

### ISSUE THREAD

**Issue by heatdream** [cryptic-game/frontend#176]
**Describe the bug**
Jedes mal wenn Geld auf das Konto eingeht, und man befindet sich im ,,Change Wallet“ Screen wird man bei einer Überweisung zurück in das Menü geworfen 

**Reproduce**
Open Wallet App
Set Miner to 100% (for the Speed)
Go to Wallet App
Go to ,,Change Wallet“ 
Every time when the Number Change, the Window reset

**Logs**

https://discord.com/channels/454739001841025024/454750853967118336/740312955941290025

**Comment by Marco1314** [comment]
Ich übernehme diesen Task
