### ISSUE TITLE
2 srollbars im terminal

### ISSUE THREAD

**Issue by T2brozz** [cryptic-game/frontend#18]
Im Terminal werden 2 scrollbars angezeigt , wobei der innere nicht benutzt wird .

![grafik](https://user-images.githubusercontent.com/42860763/57643250-9f171380-75b9-11e9-9ae2-3de5ea5c0681.png)

**Comment by MaxiHuHe04** [comment]
Already fixed in experimental

**Comment by T2brozz** [comment]
oh ok
