### ISSUE TITLE
Terminal: Normalize Font

### ISSUE THREAD

**Issue by MarcelCoding** [cryptic-game/frontend#186]
**Describe the solution you'd like**
Normalize Font

**Comment by DevMimas** [comment]
@MarcelCoding what do you mean with normalize font?

**Comment by MarcelCoding** [comment]
@DevMimas Improve the Terminal Font

**Comment by DevMimas** [comment]
@MarcelCoding Ok und in welcher Art und Weise soll die Schrift im Terminal verbessert werden? Wäre gut es etwas genauer in die Beschreibung zu packen.
