### ISSUE TITLE
Duplication of the start PC

### ISSUE THREAD

**Issue by iiestIT** [cryptic-game/frontend#187]
**Describe the bug**
I destroyed the start pc and then i tried to rebuild it. I selected all form fields and then I got an error. After Shift + F5 i got the start pc two times.

**Reproduce**
like above 

**Logs**
https://discordapp.com/channels/454739001841025024/501809431323869194/755156094397186229 
https://discordapp.com/channels/454739001841025024/501809431323869194/755155854495580250

**Additional Comments**
> I think that's the same bug as Nibiru (https://discordapp.com/channels/454739001841025024/454750853967118336/754762234760003664)

**Comment by MaxiHuHe04** [comment]
You can't disassemble the starter device anymore, so this should be fixed now.
