### ISSUE TITLE
Oberfläche wird nicht richtig angezeigt

### ISSUE THREAD

**Issue by anbonto** [cryptic-game/frontend#190]
**Describe the bug**
Bei der einblende sieht man kurz die ganze Oberfläche danach nur noch oben ein stück (wie auf den Bildern zu sehen)

**Logs**
fertig geladen:
![Screenshot from 2020-10-09 17-14-27](https://user-images.githubusercontent.com/35229590/95600897-0c4f0280-0a53-11eb-9ccb-f98ac3dc3908.png)
einblende(funktioniert trotzdem):
![Screenshot from 2020-10-09 17-19-06](https://user-images.githubusercontent.com/35229590/95601401-afa01780-0a53-11eb-867c-b2a7f2a48618.png)

**Additional Comments**
Ich nutze das Betriebsystem Ubuntu

**Comment by anba3141** [comment]
der fehler ist statisch vorhanden also immer wenn ich versuch einen computer anzeigen zu lassen bzw. auch wenn ich die seite neu lade

**Comment by JannikEmmerich** [comment]
Bei mir tritt dieses Problem leider nicht auf, kannst du bitte mal die Seite ohne Cache neuladen?

**Comment by anba3141** [comment]
cache löschen hat nichts gebracht, könnte es an meinem browser (google chrome) liegen?

**Comment by JannikEmmerich** [comment]
Du könntest mal einen Browser nehmen, bei dem du keine Add-Ons installiert hast (evtl. sind auch die Add-Ons im privaten Browser deaktiviert, dann könntest du das da testen).

**Comment by anba3141** [comment]
aus irgendnem grund funktioniert es jetzt, aber manchmal werden die bilder von manchen sachen noch nicht richtig angezeikt (das geht aber weg wenn ich die seite neu lade) und manchmal steht wenn ich die seite neu lade der fehler code: 404 not found

**Comment by JannikEmmerich** [comment]
Aktuell läuft unser Frontend nicht mehr auf https://play.cryptic-game.net, deshalb der `404 Not Found`.
Da wir allerdings PWA Support haben, lädt der Service Worker von Angular die Seite dennoch, allerdings mit den Fehlern, die du beschrieben hast.
Lösche also am besten die Service Worker:
`Strg + Shift + I` -> `Application` -> `Service Workers` -> `https://play.cryptic-game.net/` -> `Unregister`
und verwende https://play.test.cryptic-game.net.

**Comment by anba3141** [comment]
ok, danke für die hilfe

**Comment by Tristan-H11** [comment]
The service worker got removed in #314.
