### ISSUE TITLE
Miner-Wert wird nicht angezeigt

### ISSUE THREAD

**Issue by DevMimas** [cryptic-game/frontend#192]
**Describe the bug**
Der Miner-Wert wird beim ersten einschalten nicht angezeigt.

**Reproduce**
1. Neue Wallet-ID im Miner eingeben (Miner das erste mal starten)
2. Schieberegler auf 100% stellen (einschalten)
3. der Miner-Wert wird nicht angezeigt

**Additional Comments**
Erst beim erneutem öffnen des Fensters, wird der Wert angezeigt.

**Screenshot**
![grafik](https://user-images.githubusercontent.com/44207756/95691602-884a7580-0c20-11eb-96f9-be6be075278e.png)

**Comment by Tert0** [comment]
Wurde das problem mit 1e46f0b gefixed?
Falls ja kann dieser Issue geschlossen werde.
