### ISSUE TITLE
Miner-Wert nicht ausgeblendet beim deaktivieren

### ISSUE THREAD

**Issue by DevMimas** [cryptic-game/frontend#193]
**Describe the bug**
Wenn der Miner eingeschaltet ist und anschließend der Schieberegler auf 0 gestellt wird (Miner deaktiviert) bleibt der Wert erhalten. Total unlogisch, weil im deaktiviertem Zustand keine Morphcoins mehr generiert werden.

**Reproduce**
1. Miner einschalten
2. Schieberegler auf 0 setzen (deaktivieren)
3. Werte bleiben erhalten

**Additional Comments**
Die Werte müssen entweder auf 0 MC/h und 0 MC/d stehen oder ganz ausgeblendet werden. Man könnte auch anstatt 0 MC/h "_Miner ist ausgeschaltet_" schreiben.

**Screenshot**
![grafik](https://user-images.githubusercontent.com/44207756/95691645-df504a80-0c20-11eb-8b43-ba906dcaac98.png)

**Comment by Tert0** [comment]
Wurde das problem mit 1e46f0b gefixed?
Falls ja kann dieser Issue geschlossen werde.
