### ISSUE TITLE
Computer starting cheat

### ISSUE THREAD

**Issue by MathisBurger** [cryptic-game/frontend#204]
If I start my computer and I`m forwarding to another tab (for example: Inventory), the computer will start instantly without any delay.

**Comment by MathisBurger** [comment]
I think this could be fixed by using angular backgroundw-working

**Comment by MaxiHuHe04** [comment]
Hey! Thank you for this bug report. However, I wasn't able to reproduce this issue. When I start a device and navigate to another page, the device doesn't turn on at all. We will probably change that in the next release, but it is like it is supposed to work right now.
Could you please attach a screen recording (for example using ScreenToGif) to clarify?

**Comment by MaxiHuHe04** [comment]
My mistake two days ago was that I just tried to navigate to other device pages and not to the Inventory page for example like you suggested. I fixed the issue for now, but we will improve the power button further in the next release when the delay is not just a visual feature in the frontend anymore.
