### ISSUE TITLE
Move Desktop down

### ISSUE THREAD

**Issue by Akida31** [cryptic-game/frontend#208]
**Describe the bug**
If you move a window down out of the screen and click into it (for example in a terminal) the complete desktop will move down.
After that you cant move icons on the desktop.

**Reproduce**
* move a window out of the screen, click into it
second:
* move one terminal down (under the taskbar)
* click into the bottom terminal
* type sth and press enter

**Logs**
![Screenshot 2021-01-11 201611asdfsadf](https://user-images.githubusercontent.com/47895118/104227554-e1a58900-5449-11eb-8e9e-be81b9f0482e.png)

**Additional Comments**
firefox 84.0.2

**Comment by TimJ0212** [comment]
Your formatting is a bit confusing, but if I'm not mistaken, there are two problems.

1. A window is moved outside the desktop:
**Expected**: no changes to the view or shrinks the terminal.
**Actual**: the desktop scrolls to the side.

2. A window is moved outside the desktop and clicked:
**Expected**: focus is set, no change to the desktop.
**Actual**: the desktop scrolls in the respective direction.

I agree with @ClientCrash, I can also reproduce this issue only with the terminal. The command does not matter.

At the moment, I am working on a fix. The first problem is fixed: (focus() → focus({preventScroll: true})). 
The second seems to be a bit more extensive. I'll try to open a PR soon.
