### ISSUE TITLE
ESLint Migration

### ISSUE THREAD

**Issue by MarcelCoding** [cryptic-game/frontend#218]
**Is your feature request related to a problem? Please describe.**
TSLint is now deprecated.

> TSLint has been discontinued and support has been deprecated in the Angular CLI. The options shown below are for the deprecated TSLint builder. To opt-in using the community driven ESLint builder, see [angular-eslint](https://github.com/angular-eslint/angular-eslint#migrating-an-angular-cli-project-from-codelyzer-and-tslint) README.
[angular.io/cli/lint](https://angular.io/cli/lint)

**Describe the solution you'd like**
Migrate to ESLint. Add Prettier to format code independent from the IDE: #217 

**Additional Comments**
[ESLint with Prettier in Angular 11](https://dev.to/bzvyagintsev/migrate-angular-app-to-eslint-with-prettier-airbnb-styleguide-husky-and-lint-staged-862)

**Comment by MarcelCoding** [comment]
Also add stylelint

**Comment by Tristan-H11** [comment]
Done with 1344edf8040c435ecf4de25137b0f5b58b70d558.
