### ISSUE TITLE
Bruteforce Bug

### ISSUE THREAD

**Issue by GecraftetHD** [cryptic-game/frontend#224]
**Describe the bug**
> Please provide a clear and concise description of what the bug is.
If you bruteforce a PC and then the pc has been shut down while you bruteforced him, there is no terminal output.

**Reproduce**
> Steps to reproduce the behavior.
Hack a PC while he is offline, but he has to be online at the start

**Logs**
> Please provide your logs and/or screenshots of the problem.
no ;D

**Comment by Tert0** [comment]
Can some one Assing me?
