### ISSUE TITLE
Geld auf ein Wallet Transferieren wenn der Pc aus ist

### ISSUE THREAD

**Issue by Chaozz66** [cryptic-game/frontend#225]
**Describe the bug**
Es ist aktuell möglich hardware mit einem wallet zu bezahlen wo der pc offline ist.
auserderm kann man auch geld drauf transferieren oder andere miner darauf einzahlen lassen 

**Reproduce**
pc runterfahren und sich etwas überweisen lassen oder wallet id von anderen pc in seine wallet app speichern und dann anderen pc ausmachen 

**Additional Comments**
wallets auf offline pc´s dürfen weder bezahlen noch einzahlen können

**Comment by GecraftetHD** [comment]
Hä, das man geld darauf empfangen kann, ist finde ich nur logisch. Ist doch mit jeder echten Kryptowährung genauso, oder?
korrigiert mich wenn ich falsch liege.

**Comment by Tert0** [comment]
Ja. 
1. Gehört sowas ins Backend.
2. Bin ich dagegen aber auch dafür das man sonst niemanden Hacken kann bzw es Lohnt sich nicht

**Comment by JannikEmmerich** [comment]
Da das Wallet aktuell nicht wirklich an den PC gebunden ist, sondern lediglich aus wallet id + code besteht, ist dies kein frontend bug. Bitte an das Gamedesign wenden.
