### ISSUE TITLE
Neue ls Formatierung

### ISSUE THREAD

**Issue by Tert0** [cryptic-game/frontend#231]
**Is your feature request related to a problem? Please describe.**
Eine Formatierung für `ls`.
Sortiert nach Ordner oder Datei.
Und mit Farben markiert.

**Additional Comments**
Bsp:
Neue Anzeige von Dateien/Ordnern:
[FOLDER] Ordner1     | empty folder
[FOLDER] Ordner2    | contains 2 files    | 0 folder
[FOLDER] Ordner3    | contains 5 files    | 1 folder
[FILE] Datei1.txt
[FILE] wallet.wf

+ Ordner sind blau dargestellt
+ Ordner zuerst aufgelistet
+ reguläre Dateien werden nach Ordnern aufgelistet

**Comment by DevMimas** [comment]
Die Datei-Endungen, kannst du erstmal weg lassen.

**Comment by Tert0** [comment]
War nur dein Beispiel. das mit [Folder] und [File] ist eig. nicht nötig wenn man farben hat

**Comment by MarcelCoding** [comment]
--> **Englisch** <--
In the real ls folders are displayed in another color.

**Comment by DevMimas** [comment]
Joa, sehe ich bisschen anders. Woher soll man denn sofort wissen, welche Farbe für was steht?
Aber kannst [FOLDER] etc. erstmal weglassen. Kann man immer noch später schauen

**Comment by Tert0** [comment]
@DevMimas RTFM

**Comment by Tristan-H11** [comment]
LEMME COMMEMNT
