### ISSUE TITLE
Hardware Shop

### ISSUE THREAD

**Issue by Keschler** [cryptic-game/frontend#233]
**Describe the bug**
The Crossfire ZX210 costs less than the Crossfire ZX200. And it has a higher Frequency.

**Reproduce**
Go to Hardware Shop -> Ram -> DDR2

**Logs**
![Cryptic Bug](https://user-images.githubusercontent.com/62390998/105640212-1ae3ed00-5e7d-11eb-9579-18ceff4e247a.png)

**Comment by Keschler** [comment]
Oh

**Comment by Tert0** [comment]
Is this an Display Bug or an Gamedesign Bug?

**Comment by Keschler** [comment]
Gamedesgin

**Comment by Tert0** [comment]
Thats the Frontend Repo.

**Comment by Keschler** [comment]
Sorry

**Comment by Tert0** [comment]
There ist also an Gamedesign Repo.

**Comment by Keschler** [comment]
I was wrong. The stats are wrong. So its not a Gamedesign or a Display Bug

**Comment by Tert0** [comment]
What do you mean?

**Comment by Keschler** [comment]
The Frequency should be inverted.

**Comment by Tert0** [comment]
Thats an Gamedesign Bug (https://github.com/cryptic-game/cryptic-inventory/blob/master/app/vars.py).
Think they will fix this.

**Comment by Keschler** [comment]
thanks
