### ISSUE TITLE
Display Error after Login (Safari MacOS)

### ISSUE THREAD

**Issue by Dev-Fabian** [cryptic-game/frontend#239]
**Describe the bug**
> No description necessary, view screenshot.

**Reproduce**
> Open Safari on MacOS and go to "play.cryptic-game.net" and log in.

**Logs**
![Bildschirmfoto 2021-02-04 um 14 03 05](https://user-images.githubusercontent.com/45790027/106897189-e3820580-66f2-11eb-9be6-8e17adb44a2f.png)

**Comment by Dev-Fabian** [comment]
Hey Tristan,

No issues on both sides any more, looks fine.

**Comment by Tristan-H11** [comment]
Not relevant anymore.
