### ISSUE TITLE
Miner dont start

### ISSUE THREAD

**Issue by Keschler** [cryptic-game/frontend#243]
**Describe the bug**
When I started the miner with the correct UUID it did not start up. I had to change the switch where you could set the strength. Only then the Miner started.

**Reproduce**
Start the miner.

**Comment by JannikEmmerich** [comment]
Please give us a detailed description on how to reproduce the bug. Maybe include some screenshots for better understanding.

**Comment by cadamini** [comment]
Can't reproduce this. 

![miner-and-wallet](https://user-images.githubusercontent.com/1306575/145908976-7e078a8a-5f75-4951-8ab1-87356298e1d0.gif)

**Comment by Tristan-H11** [comment]
Since there was no further info, this issue is closed.
Please reopen, if this error still consists.
