### ISSUE TITLE
Terminal Icon vor Fenster plaziert

### ISSUE THREAD

**Issue by DevMimas** [cryptic-game/frontend#27]
Wenn man sich neu eingeloggt hat, dann über das Startmenü das Terminal öffnet, wird dies in der oberen rechten Ecke plaziert. Dabei steht das Terminal Icon im Vordergrund.

![grafik](https://user-images.githubusercontent.com/44207756/58374961-f9fd2300-7f48-11e9-9351-0e095da5ef8f.png)

**Comment by MaxiHuHe04** [comment]
Doesn't happen to me. Which browser did you use and is that still occurring?
