### ISSUE TITLE
Auf Handy nicht optimiert

### ISSUE THREAD

**Issue by T2brozz** [cryptic-game/frontend#30]
Auf dem Handy fängt das Terminal nicht wirklich rechts an , sondern 6 Buchtsaben danach .
Und schließen kann man die Fenster auch nicht.

![grafik](https://user-images.githubusercontent.com/42860763/58503941-e8568e00-8189-11e9-85ff-b0787dbd5698.png)

Handy: Samsung A5 2016 
Android 7.0

**Comment by use-to** [comment]
Guter Punkt! Es ist auch eine App in Planung, aber bis zu einem bestimmten Grad sollte auch dieses Frontend responsive sein.

**Comment by DevMimas** [comment]
Wieviel mehraufwand ist es denn, das Spiel zusätzlich noch für Mobile Responsive zu gestalten? Ich meine Zeit wird es definitiv kosten.
Ich denke es ist wichtiger sich erstmal auf eine Plattform zu konzentrieren, sonst spreng das echt den Rahmen.

**Comment by use-to** [comment]
Will be addressed in the future.
