### ISSUE TITLE
Touch allows empty filenames which cannot be deleted

### ISSUE THREAD

**Issue by T2brozz** [cryptic-game/frontend#31]
man kann mit touch _ text eine Datei erstellen die dann nicht aufrufbar ist (_ = space). Mit morphcoin create _ ist das nicht möglich. Die Datei kann dann auch nicht mehr gelöscht werden. 
Testdatei bei UUid:   
31fde782-a8f0-4be9-8769-e09e6d437e0a

Service ID : 
3dc8ebc3-893a-411d-8f30-7a7fea34e459
Name : deimos

**Comment by MaxiHuHe04** [comment]
@use-to I think filenames should also be validated in the backend

**Comment by MaxiHuHe04** [comment]
https://github.com/cryptic-game/cryptic-device/issues/24
