### ISSUE TITLE
Invalid Path with space at end possible

### ISSUE THREAD

**Issue by Tristan-H11** [cryptic-game/frontend#328]
**Describe the bug**
You can create folders ending with a space. This leads to a not catched error "invalid path", which is not shown to the user.

**Reproduce**
Create a new folder with the name "new-folder "

**Logs**
The blue marked text is the space.
![grafik](https://user-images.githubusercontent.com/45330667/156628611-00185bb8-abdb-491e-96d7-f00d0b07b77d.png)

**Comment by TimJ0212** [comment]
I am just looking at the problem and I found the place (file-manager.component.ts#createDirectory()). It looks like there is already a suitable exception handling. The check would need to be adjusted (also/for the best solution) in the backend.
This would have to throw the exception via the websocket.
```ts
newFolder(name: string) {
    this.fileService.createDirectory(this.delegate.device.uuid, name, this.currentFolder.uuid).subscribe({
      error: (e: Error) => {
        [...]
        if (e.message === 'invalid_input_data') {
          this.displayError('The specified folder name is not valid.');
        } 
        [...]
      }
    });
  }
```

**Comment by Tristan-H11** [comment]
@TimJ0212 Very nice! Already figured out, that the backend needs to update their validations here. I'm going to create an issue later on.

**Comment by Tristan-H11** [comment]
@Defelo

**Comment by Defelo** [comment]
fixed in https://github.com/cryptic-game/cryptic-device/pull/104
