### ISSUE TITLE
Change bruteforce terminal-output

### ISSUE THREAD

**Issue by Tristan-H11** [cryptic-game/frontend#329]
**Is your feature request related to a problem? Please describe.**
A user should see something like "please type 'stop' when you think you're PC calculated the attack for long enough". At the moment, a user does not about having to stop manually, if he does not read the wiki.
![grafik](https://user-images.githubusercontent.com/45330667/156629062-c38dddeb-8630-491e-b469-a363b89af59e.png)

**Comment by Akida31** [comment]
The new GD for FE document will define the output of the commands in the long run (currently `service bruteforce` is on page 74). Please change it there and the new shell (#258) should fix that.

**Comment by Tristan-H11** [comment]
@Akida31 perfect. Thank you.
