### ISSUE TITLE
LS, L, DIR - Commands should show a prefix oder suffix

### ISSUE THREAD

**Issue by Tristan-H11** [cryptic-game/frontend#330]
**Is your feature request related to a problem? Please describe.**
The user does not know the difference between blue and white entries. 
![grafik](https://user-images.githubusercontent.com/45330667/156629801-8a5d5cdd-6b99-45fd-8658-4a7ca7ea7d1a.png)

**Describe the solution you'd like**
There should be additional info about what is shown. For example:
[DIR] lorem
[DIR] ipsum
[FIL] file1.txt
[FIL] file2.txt

**Comment by EggerWebdesign** [comment]
You can already activate this in the Settings app @Tristan-H11

**Comment by Tristan-H11** [comment]
My thought was to enable it on default, but we can leave it as is. You're right.
