### ISSUE TITLE
Command args do not get saved in the terminal history

### ISSUE THREAD

**Issue by GecraftetHD** [cryptic-game/frontend#332]
**Describe the bug**
When entering a command in the terminal the command does not get saved completely in the command history. Only the command group gets saved. This happens also when using the upArrow button on the keyboard.

**Reproduce**
Enter a command with args and then look in your history

**Logs**
No Logs. 
**Additional Comments**
Happens in 2.2
I don't know if this is a feature ^^

**Comment by Tristan-H11** [comment]
This is indeed a bug and not a feature. Thank you for submitting it! We will consider it in our frontend prioritization and ask for further information if needed. :)
