### ISSUE TITLE
Update Page Title

### ISSUE THREAD

**Issue by ClientCrash** [cryptic-game/frontend#342]
The page title should be something like 'Cryptic' or 'Cryptic - Version' but it is this
![image](https://user-images.githubusercontent.com/40364569/157993610-1f6ae5f3-6d96-4d1c-8328-cd9becaa1c82.png)
instead. 
This looks like some standard angular config or something.

**Comment by Tristan-H11** [comment]
This is already fixed in the dev build (https://cryptic.pages.dev/) and waits to be merged.
