### ISSUE TITLE
clear line with ctrl + c

### ISSUE THREAD

**Issue by TheCataliasTNT2k** [cryptic-game/frontend#35]
Clear the input line or interrupt command (input of command) by pressing ctrl + c
example: "hel 'ctrl + c'" -> "hel^c"
copy and paste via ctrl + shift + c / v
implement context menu or "ctrl + shift + c" before implementing "ctrl + c" to interrupt programs :)
otherwise you cant copy uuids anymore

**Comment by MaxiHuHe04** [comment]
You can now do that with `CTRL + D`. In my opinion `CTRL + C` is too conflicting with copying and clearing the input line isn't as important as copying something.
