### ISSUE TITLE
Inconsistency of password length on signup 

### ISSUE THREAD

**Issue by FoseFx** [cryptic-game/frontend#4]
## Description

Setup component requires a minimum of 4 characters for a valid password, backend requires 9 characters. [Proof](https://github.com/cryptic-game/cryptic-user/blob/f275e4bd7ec199f56d3b442db0c7300856745217/app/resources/auth.py#L94)

## Reproduce

1. Signup with a 4 character password
2. Error

## Expected behavior

Warn the user if the password's length is smaller than 9 instead of 4. 

## System
No need.

**Comment by MaxiHuHe04** [comment]
Fixed, both require at least 8 letters now.
