### ISSUE TITLE
Hardwareshop-App

### ISSUE THREAD

**Issue by SpartanerSpaten** [cryptic-game/frontend#52]
## Description
Der Hardwareshop ist eine App, die man über den Desktop und im Startmenü per Icon öffnen kann. 
siehe [GDD Pre-Alpha 2](https://docs.google.com/document/d/19vbkEj5b9yNcFleT_xenGznNDC-IYJoNp7RyUcDfXNk/edit#)

## Additional context
Ist der Globaler Händler
Der Hardwareshop ist da, um neue Hardware Komponenten zu kaufen. Diese gekauften Teile können dann genutzt werden um den Computer zu upgraden und die Leistung zu verbessern. Die Hardware Teile werden in Kategorien sortiert (z.B. Festplatten) diese Kategorien werden wiederum in Unterkategorien sortiert (z.B. HDD und SSD).

**Der Kauf läuft folgendermaßen ab:**
1. Der User wählt die Items aus, die er kaufen will und klickt jeweils auf “In den Warenkorb”.
2. Wenn der User alle Items im Warenkorb hat, die er kaufen will, klickt er auf das Warenkorb Symbol. Dort werden alle Items, welche sich in diesem befinden, nochmal aufgelistet und der User kann auch wieder welche aus dem Warenkorb entfernen. Jedes Hardwareteil hat einen festen Namen und Preis. Die Hardware-Eigenschaften werden jeweils aufgelistet.
3. Zum Schluss klickt der User auf “Kaufen”. Um den Kauf abzuschließen, wird er dazu aufgefordert sein Wallet anzugeben. 
a. Liegen auf dem angegebenen Wallet die benötigten Morphcoin, findet die Transaktion statt und           der Inhalt des Warenkorbs wird dem Inventar des Users hinzugefügt. 
b. Sollte das nicht der Fall sein,  erscheint eine Fehlermeldung. Diese kann z.B. lauten “Sie können die Ware nicht bezahlen. Ihnen fehlen noch X Morphcoin.”

## Design for hardware features
Hier eine Design-Vorlage. So könnten die Hardwaremerkmale aufgelistet werden. Beispiel: Mainboard
Sollte das zu aufwendig sein, wegen der Sortierung, Reihenfolge und Ausgabe, dann kann es durch einfaches Auflisten vereinfacht werden, ohne Kategorien. Bedingt dadurch, dass der Shop ja noch einige Veränderungen erfährt.

![Hardwareshop_Technische Daten](https://user-images.githubusercontent.com/44207756/76266363-74442d00-6267-11ea-81f2-175783d0cf38.png)

**Comment by DevMimas** [comment]
Update Beschreibung mit Bild
