### ISSUE TITLE
Taskmanager-App

### ISSUE THREAD

**Issue by DevMimas** [cryptic-game/frontend#55]
## Description
Progammfenster Taskmanager zeigt die aktuelle Systemleistung an - CPU, RAM, Temperatur.

## Additional context
Achtung! Temperatur ist in der v2 noch nicht vorgesehen ggf. nur UI erstellen.

Funktionen: Programm kann geschlossen und minimiert werden. Hat eine feste Größe.

## UI Design
![Taskmanager_v3](https://user-images.githubusercontent.com/44207756/62422416-adedfd80-b6b2-11e9-9daf-8b341fa8039c.png)

**Comment by use-to** [comment]
Duplication? #48

**Comment by MaxiHuHe04** [comment]
Implemented in experimental branch
