### ISSUE TITLE
Filemanager-App

### ISSUE THREAD

**Issue by DevMimas** [cryptic-game/frontend#57]
## Description
Der Dateimanager listet die erstellten Dateien und Ordner auf.

## Additional context
Funktionen:
- Auflistung der Dateien & Ordnerstruktur
- (Größe der Datei anzeigen, wahrscheinlich noch nicht möglich --> zu klären)
- Datei öffnen - siehe Texteditor #154 
- Ordner öffnen
- App kann minimiert, maximiert, geschlossen werden

Option:
- Ordner erstellen/löschen/umbennen 
- Datei in Ordner kopieren/verschieben
  - wenn zu aufwendig nur ein Teil implementieren oder in nächste Version verschieben 
  -->Info dann an @DevMimas 

**Folder**
If you double click on a folder in the file manager, the folder is opened and displayed all next folders.

## Icons from design repo
[Filemanager-App icon](https://github.com/cryptic-game/graphics/tree/master/icons/filemanager)
[Folder icon](https://github.com/cryptic-game/graphics/blob/master/icons/folder/folder.svg)
[Textfile icon](https://github.com/cryptic-game/graphics/tree/master/icons/textdocument)

Bei Fragen an @DevMimas wenden.

**Comment by use-to** [comment]
Waiting for directory implementation on cryptic-device.

**Comment by janekx21** [comment]
i can do this

**Comment by DevMimas** [comment]
Beschreibung aktualisiert @janekx21 @MaxiHuHe04

**Comment by JannikEmmerich** [comment]
@Marco1314 are you still working on this issue?
