### ISSUE TITLE
Miner layout changes sometimes

### ISSUE THREAD

**Issue by T2brozz** [cryptic-game/frontend#65]
Wenn man 0,x morphcoin miened verschiebt sich das mc/s nach links.
![2019-08-25-17-37-09](https://user-images.githubusercontent.com/42860763/63707596-911c9400-c832-11e9-9728-a9ece6de5eb9.gif)

**Comment by MaxiHuHe04** [comment]
Wie sollte das denn sonst sein? Das ganze `0.x MC/s` bleibt halt immer zentriert

**Comment by T2brozz** [comment]
naja ich meine das das mc/s manchmal ein leerzeichen nach links rutscht so bei 0,1;0,2;0,3; usw.
