### ISSUE TITLE
new terminal commands

### ISSUE THREAD

**Issue by T2brozz** [cryptic-game/frontend#67]
Hier sind teilweise neue Befehle fürs Terminal 
https://docs.google.com/spreadsheets/d/1coYvdnfXalV-qiXkxBssXxLUaympnBeLtmZxQCYBe7g/edit#gid=0

die Network Befehle sind alle schon drin

Fragen an @T2broZz

**Comment by JannikEmmerich** [comment]
Fehlende Commands sind rot hinterlegt

**Comment by Tert0** [comment]
Miner command wurde in andere Form implementiert.
Siehe Pull Request #215

**Comment by Tert0** [comment]
Geänderte Version: https://docs.google.com/spreadsheets/d/1coYvdnfXalV-qiXkxBssXxLUaympnBeLtmZxQCYBe7g/edit?usp=sharing

**Comment by Tristan-H11** [comment]
@Akida31 does your terminal or shell PR/Draft close this?

**Comment by Akida31** [comment]
The draft is far away from being finished. Also I think this spreadsheet is outdated because there is WIP in the GD for FE document which changes the terminal commands quite a bit. So my draft will use the GDD as a base and not this spreadsheet.

**Comment by Tristan-H11** [comment]
Thinking the same. If you need any help or input, feel free to ask here or on our discord!
