### ISSUE TITLE
Settings Window

### ISSUE THREAD

**Issue by janekx21** [cryptic-game/frontend#73]
## Description
A really simple settings window that can change local settings like:
### essential
- visual settings
  - background image
  - terminal colors
  - icon pack
  - dark mode
- reset local storage button
- delete account

### optional
- account options
  - change password
  - change username
  - resend email
- load custom css

## Problem

- implementation not completed
- image assets missing

## Additional context

currently looks like this:

![image](https://user-images.githubusercontent.com/5657487/65523816-1a37f100-deed-11e9-9332-1eeda0e80de2.png)
![image](https://user-images.githubusercontent.com/5657487/65523928-418ebe00-deed-11e9-995c-c13096425d91.png)

**Comment by JannikEmmerich** [comment]
In the backend, there are missing endpoints for the requested features (like change username or delete account)
