### ISSUE TITLE
permit only one "miner-app" window

### ISSUE THREAD

**Issue by TheCataliasTNT2k** [cryptic-game/frontend#75]
## Description

It is possible to open multiple windows of the "Miner" program. This should not be possible.

## Reproduce

1. Open "Miner". 
2. Repeat step 1 ;)

## Expected behaviour

If a Miner windows is already open (even if it is minimized), this should become active and be placed on top of all other windows in the foreground, but there should not be a second one.

## Screenshots (if appropriate)
https://imgur.com/4P1daPg.png

**Comment by JannikEmmerich** [comment]
See #77
