### ISSUE TITLE
Startmenu: add shutdown-function

### ISSUE THREAD

**Issue by DevMimas** [cryptic-game/frontend#78]
## Description
Wird über das Startmenü der Button “**Ausschalten**” ![Ausschalten_klein](https://user-images.githubusercontent.com/44207756/80864122-e8f08200-8c80-11ea-9e32-27f61f03b641.png) angeklickt, wird die Ausschaltanimation #50 angezeigt und der Computer schaltet sich aus. Nach Ablauf der Animation gelangt man zum Control-Center #77 

> Hinweis:
> Start- und Ausschaltanimation aus #50 kann erstmal ein und die selbe sein, läuft praktisch beim ausschalten nur rückwärts ab.

**Logout**
Klickt der Spieler auf **Logout** melde sich der Spieler im Account ab. Der Computer bleibt dabei eingeschaltet. In der Zeit ist der Computer auch angreifbar.

## Icon from design repo
[ON/OFF icon](https://github.com/cryptic-game/graphics/blob/master/icons/startmenu/computer_on_off.svg)

## Design
![Desktop_Alpha_v4_Startmenu](https://user-images.githubusercontent.com/44207756/66276843-c509c100-e896-11e9-8da4-e623d90816c6.png)

**Comment by DevMimas** [comment]
Update the description

**Comment by JongamerProgramming** [comment]
ich möchte das issue übernehmen

**Comment by DevMimas** [comment]
The animation for switching on and off is moved to the next version
