### ISSUE TITLE
Hardware exchange between players

### ISSUE THREAD

**Issue by DevMimas** [cryptic-game/frontend#87]
## Description
Einfaches senden der Hardware an einen anderen Spieler ohne Geld.
Im Frontend wird durch einen Button neben der Hardware der Text “Versenden” angezeigt wodurch sich ein Kontextmenü öffnet in dem man die Spieler-UUID auswählen kann. 

## Additional context
Backend stellt ein Endpoint bereit, dass man ein Item aus seinem Inventory einem anderen Spieler schicken kann.

Bei Fragen an @DevMimas wenden.

**Comment by JannikEmmerich** [comment]
See #51
