### ISSUE TITLE
Desktop scaling on Monitor size

### ISSUE THREAD

**Issue by Dev-Fabian** [cryptic-game/frontend#88]
Die Icons, Programmfenster und die Task-Leiste, also die gesamte Oberfläche nach dem Login, soll nach der Monitor Größe skaliert werden.

Beispiel:

Bis jetzt:
Auf meinem 12,5 Zoll Bildschirm braucht der Task-Manager, wenn ich alle Funktionen sehen will fast den halben Bildschirm. 

Nach Skalierung:
Danach sollte der Task-Manager auf meinem 12,5 Zoll Bildschirm mit allen Funktionen nicht mehr so viel Fläche in Anspruch nehmen.

**Comment by JannikEmmerich** [comment]
See #56
